### ISSUE TITLE
Glossaries warning

### ISSUE THREAD

**Issue by shcaba** [pfmc-assessments/sa4ss#28]
I am getting the following warning and not sure if this is common or what to do about it:
Package glossaries Warning: No language module detected for `english'.
(glossaries)                Language modules need to be installed separately.
(glossaries)                Please check on CTAN for a bundle called
(glossaries)                `glossaries-english' or similar.

SO far seems not to affect the document, but any recommended fix is appreciated.

**Comment by kellijohnson-NOAA** [comment]
The package is not part of the tinytex install, so you have to install it.
There are instructions in the README how to get rid of this warning but I am guessing we need to add the install automatically when people install sa4ss.
```
tinytex::tlmgr_install(pkgs="glossaries-english")
```

**Comment by kellijohnson-NOAA** [comment]
Looks like it, but I am not positive. Did you try looking at the log file that was referenced to see if there is helpful information in it?

**Comment by kellijohnson-NOAA** [comment]
[This](https://community.rstudio.com/t/tinytex-install-missing-latex-packages-behind-firewall/62303/2) could be helpful but [this github issue on tinytex](https://github.com/yihui/tinytex/issues/126) appears to have actual instructions.

**Comment by kellijohnson-NOAA** [comment]
### :trophy:
The [help file for glossaries on CTAN](https://mirror2.sandyriver.net/pub/ctan/macros/latex/contrib/glossaries/glossaries-user.pdf) documents that if you need user-defined language help for glossaries then the additional package will need to be installed. It tries to do it automatically but it might be made more difficult when using tinytex instead of TexLive because it has to install the package. So, for users of {sa4ss}, you might need to install {glossaries-english}.
